apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kiali-operator
  template:
    metadata:
      labels:
        name: kiali-operator
    spec:
      serviceAccountName: kiali-operator
      containers:
        - name: kiali-operator
          # Replace this with the built image name
          image: kiali/kiali-operator
          command:
          - kiali-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kiali-operator"
